config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# Read all tasks
get '/tasks', to: 'tasks#index' # displays all tasks
# Create a new task
get '/tasks/new', to: 'tasks#new' # displays an empty form
post '/tasks', to: 'tasks#create' # creates a new instance
#Read one task
get '/tasks/:id', to: 'tasks#show', as: 'task'
# Update a task
get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task' # displays a prefilled form
patch '/tasks/:id', to: 'tasks#update' # patch a new undated instance to server
# Delete a task
delete '/tasks/:id', to: 'tasks#destroy', as: 'destroy_task' # deletes the task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # An option to get rid of the "@task = Task.find(params[:id])" in many of the actions below
  # before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new # don't quite understand why this needs to be there.
  end

  def create
    @task = Task.create(strong_task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(strong_task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def strong_task_params # You specify which keys in the params hash you allow
    params.require(:task).permit(:title, :details, :completed)
  end

  # def before_action
  #   @task = Task.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to 'See all tasks', tasks_path %>




<!-- How does this file know that it should put values into the form??? -->

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task)  %></li>
  <% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<% if @task.completed %>
<p> This task is completed</p>
<% else %>
<p>This task is not completed yet</p>
<% end %>

<%= link_to 'See all tasks', tasks_path %>

<%= link_to 'Edit this task', edit_task_path(@task) %>

<%= link_to 'Delete this task', destroy_task_path(@task), method: :delete, data: { confirm: "Are you sure you want to delete this task?" } %>